# Generated by Django 5.2.8 on 2026-03-05 11:37

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_name",
                    models.CharField(max_length=100, verbose_name="タスク名"),
                ),
                ("target_hours", models.IntegerField(verbose_name="目標時間（分）")),
                (
                    "completed_hours",
                    models.IntegerField(default=0, verbose_name="達成時間（分）"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "マスタータスク",
                "verbose_name_plural": "マスタータスク",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_exp",
                    models.IntegerField(default=0, verbose_name="累計経験値"),
                ),
                (
                    "rank",
                    models.CharField(
                        default="Iron", max_length=20, verbose_name="称号"
                    ),
                ),
                (
                    "current_streak",
                    models.IntegerField(default=0, verbose_name="現在の継続日数"),
                ),
                (
                    "max_streak",
                    models.IntegerField(default=0, verbose_name="最高継続日数"),
                ),
                (
                    "last_activity_date",
                    models.DateField(blank=True, null=True, verbose_name="最終活動日"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ユーザープロフィール",
                "verbose_name_plural": "ユーザープロフィール",
            },
        ),
        migrations.CreateModel(
            name="DailyMission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_minutes", models.IntegerField(verbose_name="目標時間（分）")),
                (
                    "completed_minutes",
                    models.IntegerField(default=0, verbose_name="達成時間（分）"),
                ),
                (
                    "date",
                    models.DateField(default=datetime.date.today, verbose_name="日付"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="完了フラグ"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
                (
                    "master_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tasks.mastertask",
                        verbose_name="マスタータスク",
                    ),
                ),
            ],
            options={
                "verbose_name": "デイリーミッション",
                "verbose_name_plural": "デイリーミッション",
                "ordering": ["-date"],
                "unique_together": {("user", "master_task", "date")},
            },
        ),
    ]
